from pathlib import Path

root = Path('.')
files = {
    'pipeml/core/models.py': '''from __future__ import annotations\n\nfrom dataclasses import dataclass, field\nfrom typing import Any\n\nimport numpy as np\n\n\n@dataclass\nclass PipelineContext:\n    \"\"\"Shared state passed between pipeline stages.\"\"\"\n\n    dataset_name: str\n    X: np.ndarray | None = None\n    y: np.ndarray | None = None\n    feature_names: list[str] | None = None\n    target_name: str | None = None\n    X_train: np.ndarray | None = None\n    X_test: np.ndarray | None = None\n    y_train: np.ndarray | None = None\n    y_test: np.ndarray | None = None\n    predictions: np.ndarray | None = None\n    probabilities: np.ndarray | None = None\n    model: Any = None\n    metrics: dict[str, float] = field(default_factory=dict)\n    confusion_matrix: np.ndarray | None = None\n    classification_report: str = \"\"\n    roc_auc: float | None = None\n    cross_val_score: float | None = None\n    error_rows: list[dict[str, Any]] = field(default_factory=list)\n    feature_importance: np.ndarray | None = None\n    metadata: dict[str, Any] = field(default_factory=dict)\n''',
    'pipeml/filters/base.py': '''from __future__ import annotations\n\nfrom abc import ABC, abstractmethod\n\nfrom pipeml.core.models import PipelineContext\n\n\nclass BaseFilter(ABC):\n    \"\"\"Base class for every filter in the pipeline.\"\"\"\n\n    def __init__(self, name: str | None = None) -> None:\n        self.name = name or self.__class__.__name__\n\n    @abstractmethod\n    def run(self, context: PipelineContext) -> PipelineContext:\n        raise NotImplementedError\n''',
    'pipeml/filters/data_loader.py': '''from __future__ import annotations\n\nfrom pipeml.core.models import PipelineContext\nfrom pipeml.filters.base import BaseFilter\n\n\nclass DataLoader(BaseFilter):\n    \"\"\"Load a built-in scikit-learn dataset.\"\"\"\n\n    def __init__(self, dataset_name: str = \"breast_cancer\") -> None:\n        super().__init__(name=\"DataLoader\")\n        self.dataset_name = dataset_name\n\n    def run(self, context: PipelineContext | None = None) -> PipelineContext:\n        raise NotImplementedError\n''',
    'pipeml/filters/data_validator.py': '''from __future__ import annotations\n\nfrom pipeml.core.models import PipelineContext\nfrom pipeml.filters.base import BaseFilter\n\n\nclass DataValidator(BaseFilter):\n    \"\"\"Validate the pipeline context before processing.\"\"\"\n\n    def __init__(self) -> None:\n        super().__init__(name=\"DataValidator\")\n\n    def run(self, context: PipelineContext) -> PipelineContext:\n        raise NotImplementedError\n''',
    'pipeml/filters/data_cleaner.py': '''from __future__ import annotations\n\nfrom pipeml.core.models import PipelineContext\nfrom pipeml.filters.base import BaseFilter\n\n\nclass DataCleaner(BaseFilter):\n    \"\"\"Clean the feature matrix.\"\"\"\n\n    def __init__(self) -> None:\n        super().__init__(name=\"DataCleaner\")\n\n    def run(self, context: PipelineContext) -> PipelineContext:\n        raise NotImplementedError\n''',
    'pipeml/filters/feature_engineer.py': '''from __future__ import annotations\n\nfrom pipeml.core.models import PipelineContext\nfrom pipeml.filters.base import BaseFilter\n\n\nclass FeatureEngineer(BaseFilter):\n    \"\"\"Add engineered features to the dataset.\"\"\"\n\n    def __init__(self) -> None:\n        super().__init__(name=\"FeatureEngineer\")\n\n    def run(self, context: PipelineContext) -> PipelineContext:\n        raise NotImplementedError\n''',
    'pipeml/filters/train_test_splitter.py': '''from __future__ import annotations\n\nfrom pipeml.core.models import PipelineContext\nfrom pipeml.filters.base import BaseFilter\n\n\nclass TrainTestSplitter(BaseFilter):\n    \"\"\"Split the data into train and test sets.\"\"\"\n\n    def __init__(self, test_size: float = 0.2, random_state: int = 42) -> None:\n        super().__init__(name=\"TrainTestSplitter\")\n        self.test_size = test_size\n        self.random_state = random_state\n\n    def run(self, context: PipelineContext) -> PipelineContext:\n        raise NotImplementedError\n''',
    'pipeml/filters/scaler.py': '''from __future__ import annotations\n\nfrom pipeml.core.models import PipelineContext\nfrom pipeml.filters.base import BaseFilter\n\n\nclass Scaler(BaseFilter):\n    \"\"\"Standardize numerical features.\"\"\"\n\n    def __init__(self) -> None:\n        super().__init__(name=\"Scaler\")\n\n    def run(self, context: PipelineContext) -> PipelineContext:\n        raise NotImplementedError\n''',
    'pipeml/filters/model_trainer.py': '''from __future__ import annotations\n\nfrom pipeml.core.models import PipelineContext\nfrom pipeml.filters.base import BaseFilter\n\n\nclass ModelTrainer(BaseFilter):\n    \"\"\"Train the chosen classifier.\"\"\"\n\n    def __init__(self, model_name: str = \"random_forest\") -> None:\n        super().__init__(name=\"ModelTrainer\")\n        self.model_name = model_name\n\n    def run(self, context: PipelineContext) -> PipelineContext:\n        raise NotImplementedError\n''',
    'pipeml/filters/predictor.py': '''from __future__ import annotations\n\nfrom pipeml.core.models import PipelineContext\nfrom pipeml.filters.base import BaseFilter\n\n\nclass Predictor(BaseFilter):\n    \"\"\"Generate predictions for the test set.\"\"\"\n\n    def __init__(self) -> None:\n        super().__init__(name=\"Predictor\")\n\n    def run(self, context: PipelineContext) -> PipelineContext:\n        raise NotImplementedError\n''',
    'pipeml/filters/evaluator.py': '''from __future__ import annotations\n\nfrom pipeml.core.models import PipelineContext\nfrom pipeml.filters.base import BaseFilter\n\n\nclass Evaluator(BaseFilter):\n    \"\"\"Compute evaluation metrics.\"\"\"\n\n    def __init__(self) -> None:\n        super().__init__(name=\"Evaluator\")\n\n    def run(self, context: PipelineContext) -> PipelineContext:\n        raise NotImplementedError\n''',
    'pipeml/filters/error_analyzer.py': '''from __future__ import annotations\n\nfrom pipeml.core.models import PipelineContext\nfrom pipeml.filters.base import BaseFilter\n\n\nclass ErrorAnalyzer(BaseFilter):\n    \"\"\"Inspect misclassifications and weaknesses.\"\"\"\n\n    def __init__(self) -> None:\n        super().__init__(name=\"ErrorAnalyzer\")\n\n    def run(self, context: PipelineContext) -> PipelineContext:\n        raise NotImplementedError\n''',
    'pipeml/filters/report_generator.py': '''from __future__ import annotations\n\nfrom pipeml.core.models import PipelineContext\nfrom pipeml.filters.base import BaseFilter\n\n\nclass ReportGenerator(BaseFilter):\n    \"\"\"Write evaluation artifacts to disk.\"\"\"\n\n    def __init__(self, output_dir: str | None = None) -> None:\n        super().__init__(name=\"ReportGenerator\")\n        self.output_dir = output_dir\n\n    def run(self, context: PipelineContext) -> PipelineContext:\n        raise NotImplementedError\n''',
    'pipeml/pipeline/orchestrator.py': '''from __future__ import annotations\n\nfrom pipeml.core.models import PipelineContext\n\n\nclass PipelineOrchestrator:\n    \"\"\"Coordinate the overall machine learning workflow.\"\"\"\n\n    def __init__(self) -> None:\n        self.context = PipelineContext(dataset_name=\"breast_cancer\")\n\n    def run(self) -> dict[str, object]:\n        raise NotImplementedError\n''',
    'pipeml/utils/plotting.py': '''from __future__ import annotations\n\n\ndef save_confusion_matrix(*args, **kwargs):\n    raise NotImplementedError\n\n\ndef save_roc_curve(*args, **kwargs):\n    raise NotImplementedError\n\n\ndef save_feature_importance(*args, **kwargs):\n    raise NotImplementedError\n''',
    'pipeml/config.py': '''from __future__ import annotations\n\nfrom pathlib import Path\nfrom typing import Any\n\nimport yaml\n\n\ndef load_config(config_path: str | Path | None = None) -> dict[str, Any]:\n    raise NotImplementedError\n\n\ndef configure_logging(level: str = \"INFO\") -> None:\n    raise NotImplementedError\n''',
    'pipeml/main.py': '''from __future__ import annotations\n\n\ndef main() -> None:\n    print(\"PipeML scaffold is ready.\")\n\n\nif __name__ == \"__main__\":\n    main()\n''',
}
for rel_path, content in files.items():
    path = root / rel_path
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding='utf-8')
